version: '3'
services:
  webserver:
    image: nginx:mainline-alpine
    container_name: defendersundressed-server
    ports:
      - 8080:80
    volumes:
      - ./webserver:/etc/nginx/conf.d
      - ./frontend/public:/var/www/html
    restart: unless-stopped